[transport-udp]
type=transport
protocol=udp
bind=0.0.0.0:5060
local_net=172.16.0.0/12
local_net=192.168.0.0/16
local_net=10.0.0.0/8
; external_media_address=YOUR_PUBLIC_IP
; external_signaling_address=YOUR_PUBLIC_IP

; --- GENERIC SIP TRUNK (Placeholder) ---
; [my-trunk]
; type=registration
; outbound_auth=my-trunk-auth
; server_uri=sip:trunk.provider.com
; client_uri=sip:username@trunk.provider.com
;
; [my-trunk-auth]
; type=auth
; auth_type=userpass
; username=username
; password=password
;
; [my-trunk]
; type=aor
; contact=sip:trunk.provider.com
;
; [my-trunk]
; type=endpoint
; context=from-trunk
; disallow=all
; allow=ulaw,alaw
; aors=my-trunk
; outbound_auth=my-trunk-auth
;
; [my-trunk]
; type=identify
; endpoint=my-trunk
; match=trunk.provider.com


[transport-wss]
type=transport
protocol=ws
bind=0.0.0.0:8088

[2000]
type=aor
max_contacts=1
remove_existing=yes

[2000]
type=auth
auth_type=userpass
username=2000
password=5678

[2000]
type=endpoint
aors=2000
auth=2000
context=internal
direct_media=no
disallow=all
allow=ulaw,alaw

[1001]
type=aor
max_contacts=1
remove_existing=yes

[1001]
type=auth
auth_type=userpass
username=1001
password=1234

[1001]
type=endpoint
aors=1001
auth=1001
webrtc=yes
context=internal
disallow=all
allow=ulaw,alaw,opus
media_encryption=dtls
dtls_auto_generate_cert=yes
dtls_verify=fingerprint
dtls_setup=actpass
ice_support=yes
use_avpf=yes
media_use_received_transport=yes
rtcp_mux=yes
